# Site settings
title: Ronaldo B Ferreyra - Fullstack Developer
email: rbferreyra@yahoo.com
url: "https://rbferreyra.github.io" # the base hostname & protocol for your site
description: "Website pessoal - Contatos com mídias sociais"

your-name: Ronaldo B Ferreyra
your-title: Fullstack Developer

# Social settings
facebook_url: https://facebook.com/rbferreyra1
github_url: https://github.com/rbferreyra
instagram_url: https://instagram.com/rbferreyra
linkedin_url: https://www.linkedin.com/in/rbferreyra
twitter_url: https://twitter.com/rbferreyra

# Build settings
markdown: kramdown
